server:
  port: 8888
eureka:
  instance:
    hostname: s1111
  client:
    #是否注册到自身eureka服务器
    register-with-eureka: false
    #是否从其他eureka服务器上获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://s4000:4000/eureka, http://s1111:8888/eureka,http://s5000:5000/eureka;
spring:
  application:
    name: server-01